reporting:
    resource: "@ReportingBundle/Resources/config/routing.yml"
    prefix:   /

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /
test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
